version: "3.8"

services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    networks:
      - lab_net
    tty: true
    stdin_open: true
    ports:
      - "21:21"   
      - "22:22"   
      - "23:23"   
      - "80:80"   
      - "445:445" 
      - "3306:3306" 
      - "5432:5432" # PostgreSQL
    restart: unless-stopped


  auditor:
    image: kalilinux/kali-rolling
    container_name: auditor
    networks:
      - lab_net
    tty: true
    stdin_open: true
    depends_on:
      - metasploitable2
    command: /bin/bash -c "apt-get update -q && apt-get install -yq nmap netcat-traditional && tail -f /dev/null"

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.100.0/24
