FROM ubuntu:26.04@sha256:da6fc2be547864451aa253836dd926da33623312df4a9a243e35dc877c378a78

RUN apt-get update \
    && apt-get install -y --no-install-recommends libssl3t64 libcurl4t64 ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --uid 10001 lab \
    && chmod 755 /home/lab
ENV HOME=/home/lab
WORKDIR /home/lab
USER lab

ENTRYPOINT ["/sample/output"]
