FROM ubuntu:24.04@sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3

RUN apt-get update \
    && apt-get install -y --no-install-recommends libssl3t64 libcurl4t64 ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --uid 10001 lab \
    && chmod 755 /home/lab
ENV HOME=/home/lab
WORKDIR /home/lab
USER lab

ENTRYPOINT ["/sample/output"]
